name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Generate
        uses: docker://ghcr.io/mileschou/hexo
        with:
          args: hexo generate

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          branch: gh-pages
          single-commit: true
          folder: public
          clean: true
          clean-exclude: |
            .nojekyll
